<option VALUE="FILIPINO">FILIPINO</option>
                                <OPTION VALUE="AFGHAN">AFGHAN</OPTION>
                                <OPTION VALUE="ALBANIAN">ALBANIAN</OPTION>
                                <OPTION VALUE="ALGERIAN">ALGERIAN</OPTION>
                                <OPTION VALUE="AMERICAN">AMERICAN</OPTION>
                                <OPTION VALUE="ANDORRAN">ANDORRAN</OPTION>
                                <OPTION VALUE="ANGOLAN">ANGOLAN</OPTION>
                                <OPTION VALUE="ANTIGUANS">ANTIGUANS</OPTION>
                                <OPTION VALUE="ARGENTINEAN">ARGENTINEAN</OPTION>
                                <OPTION VALUE="ARMENIAN">ARMENIAN</OPTION>
                                <OPTION VALUE="AUSTRALIAN">AUSTRALIAN</OPTION>
                                <OPTION VALUE="AUSTRIAN">AUSTRIAN</OPTION>
                                <OPTION VALUE="AZERBAIJANI">AZERBAIJANI</OPTION>
                                <OPTION VALUE="BAHAMIAN">BAHAMIAN</OPTION>
                                <OPTION VALUE="BAHRAINI">BAHRAINI</OPTION>
                                <OPTION VALUE="BANGLADESHI">BANGLADESHI</OPTION>
                                <OPTION VALUE="BARBADIAN">BARBADIAN</OPTION>
                                <OPTION VALUE="BARBUDANS">BARBUDANS</OPTION>
                                <OPTION VALUE="BATSWANA">BATSWANA</OPTION>
                                <OPTION VALUE="BELARUSIAN">BELARUSIAN</OPTION>
                                <OPTION VALUE="BELGIAN">BELGIAN</OPTION>
                                <OPTION VALUE="BELIZEAN">BELIZEAN</OPTION>
                                <OPTION VALUE="BENINESE">BENINESE</OPTION>
                                <OPTION VALUE="BHUTANESE">BHUTANESE</OPTION>
                                <OPTION VALUE="BOLIVIAN">BOLIVIAN</OPTION>
                                <OPTION VALUE="BOSNIAN">BOSNIAN</OPTION>
                                <OPTION VALUE="BRAZILIAN">BRAZILIAN</OPTION>
                                <OPTION VALUE="BRITISH">BRITISH</OPTION>
                                <OPTION VALUE="BRUNEIAN">BRUNEIAN</OPTION>
                                <OPTION VALUE="BULGARIAN">BULGARIAN</OPTION>
                                <OPTION VALUE="BURKINABE">BURKINABE</OPTION>
                                <OPTION VALUE="BURMESE">BURMESE</OPTION>
                                <OPTION VALUE="BURUNDIAN">BURUNDIAN</OPTION>
                                <OPTION VALUE="CAMBODIAN">CAMBODIAN</OPTION>
                                <OPTION VALUE="CAMEROONIAN">CAMEROONIAN</OPTION>
                                <OPTION VALUE="CANADIAN">CANADIAN</OPTION>
                                <OPTION VALUE="CAPE VERDEAN">CAPE VERDEAN</OPTION>
                                <OPTION VALUE="CENTRAL AFRICAN">CENTRAL AFRICAN</OPTION>
                                <OPTION VALUE="CHADIAN">CHADIAN</OPTION>
                                <OPTION VALUE="CHILEAN">CHILEAN</OPTION>
                                <OPTION VALUE="CHINESE">CHINESE</OPTION>
                                <OPTION VALUE="COLOMBIAN">COLOMBIAN</OPTION>
                                <OPTION VALUE="COMORAN">COMORAN</OPTION>
                                <OPTION VALUE="CONGOLESE">CONGOLESE</OPTION>
                                <OPTION VALUE="COSTA RICAN">COSTA RICAN</OPTION>
                                <OPTION VALUE="CROATIAN">CROATIAN</OPTION>
                                <OPTION VALUE="CUBAN">CUBAN</OPTION>
                                <OPTION VALUE="CYPRIOT">CYPRIOT</OPTION>
                                <OPTION VALUE="CZECH">CZECH</OPTION>
                                <OPTION VALUE="DANISH">DANISH</OPTION>
                                <OPTION VALUE="DJIBOUTI">DJIBOUTI</OPTION>
                                <OPTION VALUE="DOMINICAN">DOMINICAN</OPTION>
                                <OPTION VALUE="DUTCH">DUTCH</OPTION>
                                <OPTION VALUE="EAST TIMORESE">EAST TIMORESE</OPTION>
                                <OPTION VALUE="ECUADOREAN">ECUADOREAN</OPTION>
                                <OPTION VALUE="EGYPTIAN">EGYPTIAN</OPTION>
                                <OPTION VALUE="EMIRIAN">EMIRIAN</OPTION>
                                <OPTION VALUE="EQUATORIAL GUINEAN">EQUATORIAL GUINEAN</OPTION>
                                <OPTION VALUE="ERITREAN">ERITREAN</OPTION>
                                <OPTION VALUE="ESTONIAN">ESTONIAN</OPTION>
                                <OPTION VALUE="ETHIOPIAN">ETHIOPIAN</OPTION>
                                <OPTION VALUE="FIJIAN">FIJIAN</OPTION>
                                <OPTION VALUE="FINNISH">FINNISH</OPTION>
                                <OPTION VALUE="FRENCH">FRENCH</OPTION>
                                <OPTION VALUE="GABONESE">GABONESE</OPTION>
                                <OPTION VALUE="GAMBIAN">GAMBIAN</OPTION>
                                <OPTION VALUE="GEORGIAN">GEORGIAN</OPTION>
                                <OPTION VALUE="GERMAN">GERMAN</OPTION>
                                <OPTION VALUE="GHANAIAN">GHANAIAN</OPTION>
                                <OPTION VALUE="GREEK">GREEK</OPTION>
                                <OPTION VALUE="GRENADIAN">GRENADIAN</OPTION>
                                <OPTION VALUE="GUATEMALAN">GUATEMALAN</OPTION>
                                <OPTION VALUE="GUINEA-BISSAUAN">GUINEA-BISSAUAN</OPTION>
                                <OPTION VALUE="GUINEAN">GUINEAN</OPTION>
                                <OPTION VALUE="GUYANESE">GUYANESE</OPTION>
                                <OPTION VALUE="HAITIAN">HAITIAN</OPTION>
                                <OPTION VALUE="HERZEGOVINIAN">HERZEGOVINIAN</OPTION>
                                <OPTION VALUE="HONDURAN">HONDURAN</OPTION>
                                <OPTION VALUE="HUNGARIAN">HUNGARIAN</OPTION>
                                <OPTION VALUE="ICELANDER">ICELANDER</OPTION>
                                <OPTION VALUE="INDIAN">INDIAN</OPTION>
                                <OPTION VALUE="INDONESIAN">INDONESIAN</OPTION>
                                <OPTION VALUE="IRANIAN">IRANIAN</OPTION>
                                <OPTION VALUE="IRAQI">IRAQI</OPTION>
                                <OPTION VALUE="IRISH">IRISH</OPTION>
                                <OPTION VALUE="ISRAELI">ISRAELI</OPTION>
                                <OPTION VALUE="ITALIAN">ITALIAN</OPTION>
                                <OPTION VALUE="IVORIAN">IVORIAN</OPTION>
                                <OPTION VALUE="JAMAICAN">JAMAICAN</OPTION>
                                <OPTION VALUE="JAPANESE">JAPANESE</OPTION>
                                <OPTION VALUE="JORDANIAN">JORDANIAN</OPTION>
                                <OPTION VALUE="KAZAKHSTANI">KAZAKHSTANI</OPTION>
                                <OPTION VALUE="KENYAN">KENYAN</OPTION>
                                <OPTION VALUE="KITTIAN AND NEVISIAN">KITTIAN AND NEVISIAN</OPTION>
                                <OPTION VALUE="KUWAITI">KUWAITI</OPTION>
                                <OPTION VALUE="KYRGYZ">KYRGYZ</OPTION>
                                <OPTION VALUE="LAOTIAN">LAOTIAN</OPTION>
                                <OPTION VALUE="LATVIAN">LATVIAN</OPTION>
                                <OPTION VALUE="LEBANESE">LEBANESE</OPTION>
                                <OPTION VALUE="LIBERIAN">LIBERIAN</OPTION>
                                <OPTION VALUE="LIBYAN">LIBYAN</OPTION>
                                <OPTION VALUE="LIECHTENSTEINER">LIECHTENSTEINER</OPTION>
                                <OPTION VALUE="LITHUANIAN">LITHUANIAN</OPTION>
                                <OPTION VALUE="LUXEMBOURGER">LUXEMBOURGER</OPTION>
                                <OPTION VALUE="MACEDONIAN">MACEDONIAN</OPTION>
                                <OPTION VALUE="MALAGASY">MALAGASY</OPTION>
                                <OPTION VALUE="MALAWIAN">MALAWIAN</OPTION>
                                <OPTION VALUE="MALAYSIAN">MALAYSIAN</OPTION>
                                <OPTION VALUE="MALDIVAN">MALDIVAN</OPTION>
                                <OPTION VALUE="MALIAN">MALIAN</OPTION>
                                <OPTION VALUE="MALTESE">MALTESE</OPTION>
                                <OPTION VALUE="MARSHALLESE">MARSHALLESE</OPTION>
                                <OPTION VALUE="MAURITANIAN">MAURITANIAN</OPTION>
                                <OPTION VALUE="MAURITIAN">MAURITIAN</OPTION>
                                <OPTION VALUE="MEXICAN">MEXICAN</OPTION>
                                <OPTION VALUE="MICRONESIAN">MICRONESIAN</OPTION>
                                <OPTION VALUE="MOLDOVAN">MOLDOVAN</OPTION>
                                <OPTION VALUE="MONACAN">MONACAN</OPTION>
                                <OPTION VALUE="MONGOLIAN">MONGOLIAN</OPTION>
                                <OPTION VALUE="MOROCCAN">MOROCCAN</OPTION>
                                <OPTION VALUE="MOSOTHO">MOSOTHO</OPTION>
                                <OPTION VALUE="MOTSWANA">MOTSWANA</OPTION>
                                <OPTION VALUE="MOZAMBICAN">MOZAMBICAN</OPTION>
                                <OPTION VALUE="NAMIBIAN">NAMIBIAN</OPTION>
                                <OPTION VALUE="NAURUAN">NAURUAN</OPTION>
                                <OPTION VALUE="NEPALESE">NEPALESE</OPTION>
                                <OPTION VALUE="NEW ZEALANDER">NEW ZEALANDER</OPTION>
                                <OPTION VALUE="NI-VANUATU">NI-VANUATU</OPTION>
                                <OPTION VALUE="NICARAGUAN">NICARAGUAN</OPTION>
                                <OPTION VALUE="NIGERIEN">NIGERIEN</OPTION>
                                <OPTION VALUE="NORTH KOREAN">NORTH KOREAN</OPTION>
                                <OPTION VALUE="NORTHERN IRISH">NORTHERN IRISH</OPTION>
                                <OPTION VALUE="NORWEGIAN">NORWEGIAN</OPTION>
                                <OPTION VALUE="OMANI">OMANI</OPTION>
                                <OPTION VALUE="PAKISTANI">PAKISTANI</OPTION>
                                <OPTION VALUE="PALAUAN">PALAUAN</OPTION>
                                <OPTION VALUE="PANAMANIAN">PANAMANIAN</OPTION>
                                <OPTION VALUE="PAPUA NEW GUINEAN">PAPUA NEW GUINEAN</OPTION>
                                <OPTION VALUE="PARAGUAYAN">PARAGUAYAN</OPTION>
                                <OPTION VALUE="PERUVIAN">PERUVIAN</OPTION>
                                <OPTION VALUE="POLISH">POLISH</OPTION>
                                <OPTION VALUE="PORTUGUESE">PORTUGUESE</OPTION>
                                <OPTION VALUE="QATARI">QATARI</OPTION>
                                <OPTION VALUE="ROMANIAN">ROMANIAN</OPTION>
                                <OPTION VALUE="RUSSIAN">RUSSIAN</OPTION>
                                <OPTION VALUE="RWANDAN">RWANDAN</OPTION>
                                <OPTION VALUE="SAINT LUCIAN">SAINT LUCIAN</OPTION>
                                <OPTION VALUE="SALVADORAN">SALVADORAN</OPTION>
                                <OPTION VALUE="SAMOAN">SAMOAN</OPTION>
                                <OPTION VALUE="SAN MARINESE">SAN MARINESE</OPTION>
                                <OPTION VALUE="SAO TOMEAN">SAO TOMEAN</OPTION>
                                <OPTION VALUE="SAUDI">SAUDI</OPTION>
                                <OPTION VALUE="SCOTTISH">SCOTTISH</OPTION>
                                <OPTION VALUE="SENEGALESE">SENEGALESE</OPTION>
                                <OPTION VALUE="SERBIAN">SERBIAN</OPTION>
                                <OPTION VALUE="SEYCHELLOIS">SEYCHELLOIS</OPTION>
                                <OPTION VALUE="SIERRA LEONEAN">SIERRA LEONEAN</OPTION>
                                <OPTION VALUE="SINGAPOREAN">SINGAPOREAN</OPTION>
                                <OPTION VALUE="SLOVAKIAN">SLOVAKIAN</OPTION>
                                <OPTION VALUE="SLOVENIAN">SLOVENIAN</OPTION>
                                <OPTION VALUE="SOLOMON ISLANDER">SOLOMON ISLANDER</OPTION>
                                <OPTION VALUE="SOMALI">SOMALI</OPTION>
                                <OPTION VALUE="SOUTH AFRICAN">SOUTH AFRICAN</OPTION>
                                <OPTION VALUE="SOUTH KOREAN">SOUTH KOREAN</OPTION>
                                <OPTION VALUE="SPANISH">SPANISH</OPTION>
                                <OPTION VALUE="SRI LANKAN">SRI LANKAN</OPTION>
                                <OPTION VALUE="SUDANESE">SUDANESE</OPTION>
                                <OPTION VALUE="SURINAMER">SURINAMER</OPTION>
                                <OPTION VALUE="SWAZI">SWAZI</OPTION>
                                <OPTION VALUE="SWEDISH">SWEDISH</OPTION>
                                <OPTION VALUE="SWISS">SWISS</OPTION>
                                <OPTION VALUE="SYRIAN">SYRIAN</OPTION>
                                <OPTION VALUE="TAIWANESE">TAIWANESE</OPTION>
                                <OPTION VALUE="TAJIK">TAJIK</OPTION>
                                <OPTION VALUE="TANZANIAN">TANZANIAN</OPTION>
                                <OPTION VALUE="THAI">THAI</OPTION>
                                <OPTION VALUE="TOGOLESE">TOGOLESE</OPTION>
                                <OPTION VALUE="TONGAN">TONGAN</OPTION>
                                <OPTION VALUE="TRINIDADIAN OR TOBAGONIAN">TRINIDADIAN OR TOBAGONIAN</OPTION>
                                <OPTION VALUE="TUNISIAN">TUNISIAN</OPTION>
                                <OPTION VALUE="TURKISH">TURKISH</OPTION>
                                <OPTION VALUE="TUVALUAN">TUVALUAN</OPTION>
                                <OPTION VALUE="UGANDAN">UGANDAN</OPTION>
                                <OPTION VALUE="UKRAINIAN">UKRAINIAN</OPTION>
                                <OPTION VALUE="URUGUAYAN">URUGUAYAN</OPTION>
                                <OPTION VALUE="UZBEKISTANI">UZBEKISTANI</OPTION>
                                <OPTION VALUE="VENEZUELAN">VENEZUELAN</OPTION>
                                <OPTION VALUE="VIETNAMESE">VIETNAMESE</OPTION>
                                <OPTION VALUE="WELSH">WELSH</OPTION>
                                <OPTION VALUE="YEMENITE">YEMENITE</OPTION>
                                <OPTION VALUE="ZAMBIAN">ZAMBIAN</OPTION>
                                <OPTION VALUE="ZIMBABWEAN">ZIMBABWEAN</OPTION>